/*
 * Portal Attendance API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
	"encoding/json"
)

func CoursesIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UsersIdCourseGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	var arr[5] Course
	arr[0] = Course{ Id:"0614", Name:"キャリア形成"}
	arr[1] = Course{ Id:"6091", Name:"データベースプログラミング"}
	arr[2] = Course{ Id:"9212", Name:"デザインパターン入門"}
	arr[3] = Course{ Id:"1953", Name:"C#実習"}
	arr[4] = Course{ Id:"1820", Name:"Oracle実習"}

	json.NewEncoder(w).Encode(arr)
}

func UsersIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
