/*
 * Portal Attendance API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"math/rand"
	"time"
	"net/http"
	"encoding/json"
)

func init() {
    rand.Seed(time.Now().UnixNano())
}

func CoursesIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UsersIdCourseGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	var arr[5] Course
	
	var courseNames = [] string{"プロジェクト演習","Java実習","C#実習","データベースプログラミング","Oracle実習","IT活用技法","キャリア形成","デザインパターン入門"}

	for i := range arr {
		idStr := fmt.Sprintf("%04d", rand.Intn(9999))
		arr[i] = Course{ Id:idStr, Name:courseNames[rand.Intn(len(courseNames))] }
	}

	json.NewEncoder(w).Encode(arr)
}

func UsersIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
