/*
 * Portal Attendance API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
	"encoding/json"
)

func CoursesIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func UsersIdCourseGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	var arr[5] Course
	arr[0] = Course{ Id:0, Name:"講義0" }
	arr[1] = Course{ Id:1, Name:"講義1" }
	arr[2] = Course{ Id:2, Name:"講義2" }
	arr[3] = Course{ Id:3, Name:"講義3" }
	arr[4] = Course{ Id:4, Name:"講義4" }

	json.NewEncoder(w).Encode(arr)
}

func UsersIdGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
