/*
 * Portal Attendance API
 *
 * description
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Course struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
